# Generated by Django 2.0.3 on 2018-05-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('work_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='WorkID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='Sex')),
                ('card_ID', models.CharField(default='', max_length=18, verbose_name='CardID')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='age')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Addre')),
                ('nation', models.CharField(default='', max_length=40, verbose_name='Nation')),
                ('birthplace', models.CharField(default='', max_length=100, verbose_name='BirthPlace')),
                ('phonenum', models.CharField(default='', max_length=15, verbose_name='Phone')),
                ('title', models.IntegerField(choices=[(0, '教授'), (1, '副教授'), (2, '讲师'), (3, '助理讲师')], default=2, verbose_name='Title')),
                ('firstedu', models.IntegerField(choices=[(0, '专科'), (1, '本科'), (2, '硕士'), (3, '博士'), (4, '博士后')], default=1, verbose_name='FirstEdu')),
                ('firstsch', models.CharField(default='', max_length=100, verbose_name='FirstSch')),
                ('finaledu', models.IntegerField(choices=[(0, '专科'), (1, '本科'), (2, '硕士'), (3, '博士'), (4, '博士后')], default=1, verbose_name='FinalEdu')),
                ('finalsch', models.CharField(default='', max_length=100, verbose_name='FinalSch')),
                ('honor', models.TextField(default='', verbose_name='Honor')),
                ('college', models.IntegerField(choices=[(0, '中俄学院'), (1, '哲学学院'), (2, '政府管理学院'), (3, '经济与工商管理院'), (4, '法学院'), (5, '教育科学研究学院'), (6, '文学院'), (7, '新闻传播学院'), (8, '西语学院'), (9, '俄语学院'), (10, '东语学院'), (11, '艺术学院'), (12, '历史文化旅游学院'), (13, '数学科学学院'), (14, '物理科学与技术学院'), (15, '化学化工与材料学院'), (16, '生命科学学院'), (17, '机电工程学院'), (18, '电子工程学院'), (19, '计算机科学技术学院'), (20, '软件学院'), (21, '信息科学与技术学院'), (22, '建筑工程学院'), (23, '水利电力学院'), (24, '农作物研究院'), (25, '农业资源与环境学院'), (26, '信息管理学院'), (27, '应用外语学院'), (28, '俄语语言文学中心'), (29, '马克思主义学院'), (30, '国际文化教育学院'), (31, '满族语言文化研究中心')], default=0, verbose_name='College')),
                ('entry_time', models.DateField(default='', verbose_name='EntryTime')),
                ('checkstatus', models.IntegerField(choices=[(0, '待审核'), (1, '已审核'), (2, '审核未通过')], default=0, verbose_name='CheckStu')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teacher.Teacher')),
                ('img', models.ImageField(default='img/0.jpg', upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teacher.Teacher')),
                ('password', models.CharField(max_length=15)),
                ('status', models.IntegerField(choices=[(0, 'admin'), (1, 'teacher')])),
            ],
        ),
    ]
