# Generated by Django 2.0.3 on 2018-05-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='username',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
