# Generated by Django 2.0.3 on 2018-05-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20180509_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last5',
            field=models.IntegerField(default=0, verbose_name='Last5'),
        ),
    ]
