# Generated by Django 2.0.3 on 2018-05-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_last5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='last5',
        ),
        migrations.AddField(
            model_name='teacher',
            name='rate',
            field=models.CharField(max_length=10, null=True, verbose_name='Rate'),
        ),
    ]
