# Generated by Django 2.0.3 on 2018-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20180509_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last1',
            field=models.IntegerField(default=0, verbose_name='Last1'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last2',
            field=models.IntegerField(default=0, verbose_name='Last2'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last3',
            field=models.IntegerField(default=0, verbose_name='Last3'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last4',
            field=models.IntegerField(default=0, verbose_name='Last4'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last5',
            field=models.IntegerField(default=0, verbose_name='Last5'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rate',
            field=models.IntegerField(choices=[(0, '-'), (1, 'A'), (2, 'B'), (3, 'C')], default=0, verbose_name='Rate'),
        ),
    ]
